package views;

/**
 *
 * @author LeoArc
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Lvehiculo = new javax.swing.JButton();
        Avehiculo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 25)); // NOI18N
        jLabel1.setText("Menu Principal");

        Lvehiculo.setBackground(new java.awt.Color(102, 255, 51));
        Lvehiculo.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Lvehiculo.setForeground(new java.awt.Color(51, 51, 51));
        Lvehiculo.setText("Listar Vehiculos");
        Lvehiculo.addActionListener(this::LvehiculoActionPerformed);

        Avehiculo.setBackground(new java.awt.Color(255, 0, 0));
        Avehiculo.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Avehiculo.setForeground(new java.awt.Color(51, 51, 51));
        Avehiculo.setText("Agregar Vehiculo");
        Avehiculo.addActionListener(this::AvehiculoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Lvehiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(Avehiculo)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lvehiculo)
                    .addComponent(Avehiculo))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LvehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LvehiculoActionPerformed
        
        
        ListarVehiculosView listar = new ListarVehiculosView();
        listar.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_LvehiculoActionPerformed

    private void AvehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvehiculoActionPerformed
       
        IngresarVehiculo agregar = new IngresarVehiculo();
        agregar.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_AvehiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Avehiculo;
    private javax.swing.JButton Lvehiculo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
